### ISSUE TITLE
PERMISSION_CODE_CAMERA

### ISSUE THREAD

**Issue by AppWerft** [gimdongwoo/Ti-Android-RequestStoragePermission#1]
Hi,

why do you use this permission PERMISSION_CODE_CAMERA
?

Cheers!
Rainer
Edit: self solved RTFM.

**Comment by gimdongwoo** [comment]
Sorry, I'm late.
Because, Korean traditional holiday now.

This code copy from origianl titanium project code.
That code is already exist.
