### ISSUE TITLE
Permissions popup is hidden

### ISSUE THREAD

**Issue by icecandy** [gimdongwoo/Ti-Android-RequestStoragePermission#2]
This module does seem to work, but the problem is that the Android permissions popup that asks the user for permission is behind the main Titanium window of my app so is not seen.
If one closes the app one can still see the popup and respond to it, then going back to the app the permissions have been set.
So unusable at the moment but promising.

Ti SDK 5.1.2, Android 6.0.0 I should note that I am running in Genymotion a Samsung Galaxy S6 emulator.

**Comment by icecandy** [comment]
Oh my bad. Just needed to get my events sorted and open the permissions at the right time. Working now thanks.

**Comment by gimdongwoo** [comment]
Ok, Thank you.
