### ISSUE TITLE
Callback isn't raised

### ISSUE THREAD

**Issue by balanza** [gimdongwoo/Ti-Android-RequestStoragePermission#3]
Hi,

I copy&pasted the usage snippet you provide. It correctly shows the popup and set the permission as the user does. The problem is the callback isn't raised, and I have no possibility to run any instruction on both success or failure case. 

I'm running the snippet inside `index.js` controller and testing on a `Nexus 6` with `Android 6.0.1` installed.

Thanks

**EDIT**
I'm running the snippet into `index.js`, at application start. I found the following: for the callback to work, the window open instruction `$.index.open()` must be called inside the callback, otherwise the callback isn't raised. The following snippet works:

```
var requestStoragePermission = function() {
    var RSP = require("com.boxoutthinkers.reqstorageperm");
    if (!RSP.hasStoragePermission()) {
        RSP.requestStoragePermissions(function(e) {
            if (e.success) {
                $.index.open();
            } else {
                //handle failure
            }
        });
    } else {
        Ti.API.info('requestStoragePermission : already have');
        $.index.open();
    }
};

requestStoragePermission();
```

I'm not sure if it's a bug or not, however this leads to a possibly unwanted behaviour: the permission-request popup lays over the splash screen, not over the `index«.

**Comment by gabeaguirre** [comment]
balanza, I think it's a race case based on the current activity. Basically, wait until whatever window opens last or view opens last. I had the same problem when I moved it to index.js, since my overall drawer window would open after, thus covering it.

**Comment by gimdongwoo** [comment]
Hi.
Index is root window.
If you close index, app is exited.
Therefore, requestpermission is running on opened window(index or others).

**Comment by gabeaguirre** [comment]
Thanks a lot for the module, you saved me. I made some more methods but I was having a hard time getting this right. This means I don't have to update all my modules. Thanks again.

**Comment by gimdongwoo** [comment]
It's similar to the following's "Ti.Media.requestCameraPermissions".
https://github.com/appcelerator-developer-relations/appc-sample-ti510/blob/master/app/controllers/permissions.js
Thank you.
