### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by imlordeyaya** [gimdongwoo/Ti-Android-RequestStoragePermission#4]
Hello, Im not sure if Im doing everything right. So I uploaded the module in modules directory as i do with other modules, activated it in tiapp than added  the code : `var ti_android_requeststoragepermission = require("com.boxoutthinkers.reqstorageperm");`
on top of my .js controller which needs the permission. I tested it in my android 6.0 device and the permission is still not given.
My titanium sdk is 5.3.1GA
Thanks for any help

**Comment by gimdongwoo** [comment]
You need to call method like useage section in readme.
Give your more code related this module.

**Comment by gimdongwoo** [comment]
https://github.com/gimdongwoo/Ti-Android-RequestStoragePermission/blob/master/README.md

**Comment by imlordeyaya** [comment]
Ok so I have added the code in usage to MainMenu.js controller of my app and code checkPermissions(function callback() {...}); to view MainMenu.xml and nothing happens, no dialog window and permission not given.
